### ISSUE TITLE
Link().get() fails

### ISSUE THREAD

**Issue by svinota** [jta/ipyroute#1]
```
{master} $ cat test.py 
import ipyroute
print(ipyroute.Link().get())

{master} $ python test.py 
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    print(ipyroute.Link().get())
  File "/home/peet/Projects/ipyroute/ipyroute/base.py", line 171, in get
    result = [i for i in iterator if filt(i)]
  File "/home/peet/Projects/ipyroute/ipyroute/base.py", line 170, in <genexpr>
    iterator = (cls.from_string(l, *args) for l in func())
  File "/home/peet/Projects/ipyroute/ipyroute/base.py", line 116, in from_string
    raise ValueError(msg)
ValueError: No match found for <class 'ipyroute.link.Link'>: u'5: virbr0-nic@NONE: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel master virbr0 state DOWN mode DEFAULT group default qlen 500\\    link/ether 52:54:00:17:a9:13 brd ff:ff:ff:ff:ff:ff\n'
```

**Comment by jta** [comment]
Thanks for trying this out despite complete lack of documentation!

fwiw, I did try pyroute2 but it was a bit overkill for my use case, particularly since IPDB at the time tried to ingest all the routes in table master, and my hosts have 500k routes with 4 next hops each.

**Comment by svinota** [comment]
It depends on the purpose, if you wanna do one-shot operations, sometimes it's better to use `IPRoute` than `IPDB`; for long-running programs `IPDB` works better, and for your particular cases there is now `ignore_rtables` parameter for `IPDB` that allows to skip tables that you do not wanna work with.

I continue to play with `ipyroute`, there definitely may be useful solutions I missed in my project :)

**Comment by svinota** [comment]
thanks for the readme, btw.
